### ISSUE TITLE
Build error dependency for  io.swagger:swagger-java-client:jar:1.0.0

### ISSUE THREAD

**Issue by eaudet** [eaudet/trainingbot#20]
From: Leander:

I was trying to build the project, but it failed on swagger-java-client…

Failed to execute goal on project service: Could not resolve dependencies for project com.jarics.trainbot:service:jar:1.0-SNAPSHOT: Failure to find io.swagger:swagger-java-client:jar:1.0.0 in https://repo.spring.io/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced

**Comment by SmetLeander** [comment]
@eaudet Can you provide the latest YAML for the project? The one in the service folder is outdated (6 months old), and when I build the io.swagger.client using the swagger editor, then I get those errors ;) Thanks!

**Comment by eaudet** [comment]
This probably for building trainbotui right? I will look at this today. Sorry for the delay for the response.
Erick


__________________
Erick Audet M.Sc.
email: eaudet@jarics.com
Skype:erick.audet
LinkedIn: http://www.linkedin.com/in/erickaudet
https://github.com/eaudet
mob.: 418.657.9712

**Comment by eaudet** [comment]
Ok, thanks for the precision. I will add an issue and work it out.



__________________
Erick Audet M.Sc.
email: eaudet@jarics.com
Skype:erick.audet
LinkedIn: http://www.linkedin.com/in/erickaudet
https://github.com/eaudet
mob.: 418.657.9712

**Comment by eaudet** [comment]
@SmetLeander I see to problem. The yaml file is not used anymore. I simply use Postman. I will commit changes in master branch later today.

**Comment by eaudet** [comment]
@SmetLeander I have committed the changes in master branch. The yaml files does not exist anymore. See the /trainingbot/Training Bot Postman.postman_collection.json postman project. I use eaudet for a username but you should use your own strava username. Let me know if it works.
