### ISSUE TITLE
MVN clean isntall not working

### ISSUE THREAD

**Issue by SmetLeander** [eaudet/trainingbot#23]
Hi Erick,

Where did you generate your io.swagger.client form?
The maven build still doesn't work... Sorry ;)

MVN CLEAN INSTALL
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project service: Compilation failure: Compilation failure: 
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/learning/FeatureExtractor.java:[5,31] cannot find symbol
[ERROR]   symbol:   class SummaryActivity
[ERROR]   location: package io.swagger.client.model
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/learning/FeatureExtractor.java:[16,10] cannot find symbol
[ERROR]   symbol:   class SummaryActivity
[ERROR]   location: class com.jarics.trainbot.services.learning.FeatureExtractor
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/StravaService.java:[11,29] cannot find symbol
[ERROR]   symbol:   class ActivitiesApi
[ERROR]   location: package io.swagger.client.api
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/StravaService.java:[13,31] cannot find symbol
[ERROR]   symbol:   class ActivityType
[ERROR]   location: package io.swagger.client.model
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/StravaService.java:[14,31] cannot find symbol
[ERROR]   symbol:   class DetailedActivity
[ERROR]   location: package io.swagger.client.model
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/StravaService.java:[15,31] cannot find symbol
[ERROR]   symbol:   class DetailedSegmentEffort
[ERROR]   location: package io.swagger.client.model
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/StravaService.java:[16,31] cannot find symbol
[ERROR]   symbol:   class SummaryActivity
[ERROR]   location: package io.swagger.client.model
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/StravaService.java:[62,51] cannot find symbol
[ERROR]   symbol:   class DetailedSegmentEffort
[ERROR]   location: class com.jarics.trainbot.services.StravaService
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/StravaService.java:[70,12] cannot find symbol
[ERROR]   symbol:   class DetailedActivity
[ERROR]   location: class com.jarics.trainbot.services.StravaService
[ERROR] /Users/Leander/Desktop/trainingbot/service/src/main/java/com/jarics/trainbot/services/StravaService.java:[91,37] cannot find symbol
[ERROR]   symbol:   class SummaryActivity
[ERROR]   location: class com.jarics.trainbot.services.StravaService

**Comment by eaudet** [comment]
Definitely a bug in external dependencies on io.swagger.client packages. This is my project https://github.com/eaudet/strava-api-v3.

**Comment by eaudet** [comment]
@SmetLeander I will deploy strava-api-v3 in a public maven repo. Meanwhile, you need to install strava-api-v3 in you local maven repo. Simply follow this [readme](https://github.com/eaudet/strava-api-v3/tree/master/java-client). You will be able to build after that.  Sorry, your the first so hang in there. Thanks a bunch for your patience.

**Comment by eaudet** [comment]
Working
